server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: 1234

  # 콘솔에 SQL 출력여부
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: validate

    #     hibernate.ddl-auto의 여러 옵션들설명
    #none : 사용하지 않음
    #create : 기존 테이블 삭제 후 테이블 생성 (주의)
    #create-drop : 기존 테이블 삭제 후 테이블 생성, 종료 시점에 테이블 삭제 (주의)
    #update : 변경된 스키마 적용 (주의)
    #validate : 엔티티와 테이블 정상 매핑 확인



